#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/inline"

require "yaml"
require "json"

class DokkuAppJsonGenerator
  def self.call(compose_file_path, output_path = "app.json")
    compose_config = YAML.load(File.read(compose_file_path))

    app_json_contents = compose_config.fetch("x-dokku-app-json", {})

    compose_config["services"].inject(app_json_contents) do |memo, service_name, service_config|
      memo = configure_healthchecks(memo, service_name, service_config)
      configure_formation(memo, service_name, service_config)
    end

    File.write(output_path, JSON.dump(app_json_contents))
  end

  private def self.configure_healthchecks(app_json, service_name, service_config)
    return app_json unless service_config.key?("healthcheck")
    
    app_json[:healthchecks] ||= {}

    app_json_service_config = {
      type:         service_config.dig("healthcheck", "x-dokku-type") || "startup",
      command:      service_config.dig("healthcheck", "test"),
      attempts:     service_config.dig("healthcheck", "retries"),
      initialDelay: service_config.dig("healthcheck", "interval"),
      timeout:      service_config.dig("healthcheck", "timeout"),
      wait:         service_config.dig("healthcheck", "interval"),
      httpHeaders:  service_config.dig("healthcheck", "x-dokku-http-headers"),
      path:         service_config.dig("healthcheck", "x-dokku-path"),
      port:         service_config.dig("healthcheck", "x-dokku-port"),
      scheme:       service_config.dig("healthcheck", "x-dokku-scheme")
    }.compact

    app_json.merge(healthchecks: app_json[:healthchecks].merge(service_name => app_json_service_config))
  end

  private def self.configure_formation(app_json, service_name, service_config)
    return app_json unless service_config.key?("deploy")
      
    app_json[:formation] ||= {}
    
    app_json_service_config = {
      quantity:     service_config.dig("deploy", "replicas"),
      max_parallel: service_config.dig("deploy", "update_config", "parallelism")
    }

    app_json.merge(formation: app_json[:formation].merge(service_name => app_json_service_config))
  end

  private def app_json_schema 
    @app_json_schema ||= Dry::Schema.JSON do
      optional(:cron).array(:hash) do
        required(:command).filled(:string)
        required(:schedule).filled(:string)
        optional(:maintenance).value(type?: Boolean)
        optional(:concurrency_policy).value(included_in?: %w(allow forbid replace))
      end

      optional(:scripts).hash do
        optional(:dokku).hash do
          optional(:predeploy).filled(:string)
          optional(:postdeploy).filled(:string)
        end

        optional(:postdeploy).filled(:string)
      end
    end
  end
end

DokkuAppJsonGenerator.call(*ARGV)