#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-compose-set-compose-path() {
  declare desc="Set the path to a compose.yml file"
  declare cmd="compose:set-compose-path"
  [[ "$1" == "$cmd" ]] && shift 1 

  declare APP="$1"
  declare COMPOSE_PATH="$2"

  [[ "$APP" == "--global" ]] || verify_app_name "$APP"

  fn-plugin-property-write "compose" "$APP" "compose-path" "$COMPOSE_PATH"
}

cmd-compose-report() {
  declare desc="Shows compose plugin configuration for an app"
  declare cmd="compose:report"
  [[ "$1" == "$cmd" ]] && shift 1

  declare APP="$1"

  GLOBAL_COMPOSE_PATH=$(fn-plugin-property-get "compose" "--global" "compose-path")
  echo "Global compose path: $GLOBAL_COMPOSE_PATH"

  [[ -z "$APP" ]] && exit 0

  APP_COMPOSE_PATH=$(fn-plugin-property-get "compose" "$APP" "compose-path")
  echo "App $APP compose path: $APP_COMPOSE_PATH"

  APP_JSON_CREATED=$(fn-plugin-property-get "compose" "$APP" "app-json")
  echo "App $APP using generated app.json: ${APP_JSON_CREATED:-false}"

  PROCFILE_CREATED=$(fn-plugin-property-get "compose" "$APP" "procfile")
  echo "App $APP using generated Procfile: ${PROCFILE_CREATED:-false}"
  
  # TODO: Report on resource settings.
  
  exit 0
}