#!/usr/bin/env bash

[[ " help compose:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
source "$PLUGIN_AVAILABLE_PATH/compose/help-functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | compose:help)
    cmd-compose-help "$@"
      ;;
  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
      ;;
esac