#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/compose/internal-functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-compose-git-from-directory() {
  declare APP="$1" WORK_DIR="$2"
  SOURCE_IMAGE=$(fn-plugin-property-get "git" "$APP" "source-image")
  COMPOSE_PATH=$(fn-find-compose-path "$APP")

  if [[ "$SOURCE_IMAGE" != "" ]]; then
    fn-compose-from-image "$WORK_DIR" "$SOURCE_IMAGE" "$COMPOSE_PATH"
  else
    fn-compose-from-repo "$WORK_DIR" "$COMPOSE_PATH"
  fi
}

trigger-compose-git-from-directory "$@"